[project]
name = "sentiment-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.42.97",
    "datasets>=4.8.5",
    "pandas>=3.0.2",
    "pyarrow>=24.0.0",
    "sagemaker>=3.0.1",
    "torch>=2.11.0",
    "transformers>=5.7.0",
]
