name: Deploy Lambda 

on:
  push:
    branches: [main]
    paths:
      - 'deploy/lambda/**'

env:
  AWS_REGION: us-east-1
  REPO: sentiment-pipeline
  FUNCTION_NAME: sentiment-pipeline-inference


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        env:
          IMAGE_URI: ${{ steps.login-ecr.outputs.registry }}/${{ env.REPO }}:latest
        run: |
          docker build --provenance=false -t $IMAGE_URI deploy/lambda/
          docker push $IMAGE_URI
        
      - name: Deploy to Lambda 
        env:
          IMAGE_URI: ${{ steps.login-ecr.outputs.registry }}/${{ env.REPO }}:latest
        run: |
          aws lambda update-function-code \
          --function-name ${{ env.FUNCTION_NAME }} \
          --image-uri $IMAGE_URI \
          --region ${{ env.AWS_REGION }}